{
 "title": "PyData Eindhoven 2022 demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "model_version",
    "query": {
     "query": "label_values(request_count_total, model_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(request_latency_seconds_bucket{model_version=\"${model_version}\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "description": "Number of requests per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(request_count_total{model_version=\"${model_version}\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Error rate (ratio of total requests)",
   "type": "timeseries",
   "description": "Number of errors in the requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(request_error_total{model_version=\"${model_version}\"}[$__interval]) / rate(request_count_total{model_version=\"${model_version}\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Response distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(response_distribution_bucket{le!=\"+Inf\", model_version=\"${model_version}\"}[$__range])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Model categories: region (feature 0)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(model_categorical_total{feature=\"0\"}[$__range])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Model categories: tenure (feature 1)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(model_categorical_total{feature=\"1\"}[$__range])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Model categories: top_pack (feature 2)",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(model_categorical_total{feature=\"2\"}[$__range])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "SimpleImputed data per feature",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(imputed_total[$__range])",
     "legendFormat": "{{feature}}"
    }
   ]
  }
 ]
}